
FROM qcdis/miniconda3 AS build
COPY produce-data-u1-g1-environment.yaml .
RUN conda env update -f produce-data-u1-g1-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY produce-data-u1-g1.py .

